lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/modules.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/nf-core-fetchngs_logo_light.png
    - assets/sendmail_template.txt
    - docs/images/nf-core-fetchngs_logo_dark.png
    - docs/images/nf-core-fetchngs_logo_light.png
  modules_config: false
  multiqc_config: false
nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Harshil Patel, Moritz E. Beber and Jose Espinosa-Carrasco
  description: Pipeline to fetch metadata and raw FastQ files from public databases
  force: false
  is_nfcore: true
  name: fetchngs
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
    - multiqc
  version: 1.13.0dev
