# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
name: nf-core CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master
  release:
    types:
      - "published"

env:
  NXF_ANSI_LOG: false
  NFTEST_VER: "0.7.3"

# cancel-in-progress: true ensures that if a new push is made to the same branch while a previous run is still in progress, the previous run is cancelled
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - NXF_VER: "latest-everything"
            pull_request_target: "dev"
            profile: "docker"
          - NXF_VER: "22.10.1"
            pull_request_target: "master"
            profile: "docker"
          - NXF_VER: "latest-everything"
            pull_request_target: "master"
            profile: "docker"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      # Install nf-test
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      # Run nf-test
      - name: Run nf-test
        id: nf-test
        run: |
          nf-test test tests/pipeline/ --profile "test,${{ matrix.profile }}" --tap=test.tap
          echo "tap=$(cat test.tap)" >> $GITHUB_OUTPUT

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      # Comment on the PR with the test results
      - name: Comment PR with execution number
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            _(ci_test_results **${{ steps.nf-test.outputs.tap }}** )_
          comment_tag: ci_test_results
